name: Go

on:
  push:
    branches:
      - "*" 
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Install gox
      run: |
        go get github.com/mitchellh/gox

    - name: Build
      run: gox -osarch="linux/amd64 linux/arm darwin/amd64 windows/amd64"

    - name: Test
      run: go test -v ./...

